### ISSUE TITLE
Enforce types

### ISSUE THREAD

**Issue by SzilBalazs** [bbeatrix/knpy#14]

**Comment by sulan** [comment]
# Todos

- [ ] configure mypy in `pyproject.toml`
- [ ] add type hints to `data_utils.py`
- [ ] add type hints to `Braid`
- [ ] add type hints to the unit tests
